### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by telarale** [SoftwareAgenten/Arbeit#1]
Vorschlag für weitere Vorgehensweise (wenn es so für dich passt, können wir 1 issue pro Punkt öffnen)

0. *Weiterführende Literatur* und *Literaturverzeichnis* (wachsen dynamisch mit)
1. Mit **beschreibenden** Kapiteln anfangen. **Definitionen**: Phishing, Captcha, Honeypot; Software-Agent, usw. (also *Kapitel 4* in deinem Inhaltsverzeichnis)
2. **Forschung** (Ergebnisse fließen in Implementation ein)
3. Auswertung der Forschung
4. Implementation **Software**
5. **Auswertung** der Ergebnisse
6. Schreiben der Kapitel zur Forschung (also *Kapitel 5* und *6* in deinem Inhaltsverzeichnis)
7. *Zusammenfassung* und *Einleitung*

**Comment by florianpircher** [comment]
Ich werde einige dieser Punkte als eigene Issues anlegen, dann kann ich sie leichter nach und nach abhacken.

**Comment by florianpircher** [comment]
* Literaturverzeichnis: #3 
* Weiterführende Literatur: #2 
* Definition Phishing: #4 
* Definition CAPTCHA: #5 
* Definition Honypot: #6 
* Definition Software-Agenten: #7 
* Definition Spam: #8

**Comment by telarale** [comment]
check

Date: Tue, 8 Dec 2015 03:48:30 -0800

**Comment by florianpircher** [comment]
Bewege Inhalte ins [Wiki](https://github.com/SoftwareAgenten/Arbeit/wiki/Next-Steps).
