### ISSUE TITLE
Definition für Phishing schreiben

### ISSUE THREAD

**Issue by florianpircher** [SoftwareAgenten/Arbeit#4]
* Was ist Phishing?

**Comment by florianpircher** [comment]
@telarale Passt [diese Phishing-Def](https://github.com/SoftwareAgenten/Arbeit/blob/feature/definitions/LaTeX/TeX/4.2-phishing.tex)?

**Comment by telarale** [comment]
passt gut! habe 1 2 änderungen vorgenommen. einzige inhaltliche sache: phishing kann auch von webseiten aus betrieben werden...evtl auch darauf hinweisen
evtl kurz auf die wortherkunft hinweisen in klammern bspw (phising von engl fishing = fischen) oder so ähnlich..
telarale
Date: Thu, 3 Mar 2016 09:23:13 -0800
