### ISSUE TITLE
Definition für CAPTCHA schreiben

### ISSUE THREAD

**Issue by florianpircher** [SoftwareAgenten/Arbeit#5]
* Was ist ein CAPTCHA? Welche Arten gibt es?
* Warum wurde diese Technik als Bot-sicher angesehen?

**Comment by florianpircher** [comment]
@telarale Geht [diese Definition](https://github.com/SoftwareAgenten/Arbeit/blob/develop/LaTeX/TeX/4.3-kuenstliche-intelligenz.tex) gut so?

**Comment by telarale** [comment]
Schaut gut aus. Die Definitionen passen mittlerweile alle sehr gut :)





On Thu, Mar 31, 2016 at 10:47 AM -0700, "Florian Pircher" <notifications@github.com> wrote:





@telarale Geht [diese Definition](https://github.com/SoftwareAgenten/Arbeit/blob/develop/LaTeX/TeX/4.3-kuenstliche-intelligenz.tex) gut so?

---
