### ISSUE TITLE
Definition für Spam schreiben

### ISSUE THREAD

**Issue by florianpircher** [SoftwareAgenten/Arbeit#8]
* Was ist Spam? Seit wann gibt es Spam?
* E-Mail, Kommentare, Foren

**Comment by florianpircher** [comment]
@telarale Wie sieht es mit [dieser Definition](https://github.com/SoftwareAgenten/Arbeit/blob/master/LaTeX/tex/4.1.0-spam.tex) aus?

**Comment by florianpircher** [comment]
@telarale Ist [diese Spam-Definition](https://github.com/SoftwareAgenten/Arbeit/blob/develop/LaTeX/tex/4.1-spam.tex) ausreichend oder habe ich noch etwas vergessen bzw. sollte ich die Definition noch erweitern oder verkürzen?

**Comment by telarale** [comment]
gefällt mir gut so!

Date: Sun, 7 Feb 2016 10:45:00 -0800
